### ISSUE TITLE
fix scraper

### ISSUE THREAD

**Issue by asyncfncom** [metric-space-ai/octopus_function#52]
```
Using default request storage
Created proxy listening on 127.0.0.1:39705
Exception in thread ServerThread (('127.0.0.1', 39705)):
Traceback (most recent call last):
  File "/octopus_server/services/bfbb74bc-a507-4787-8c84-71955881885c/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/octopus_server/services/bfbb74bc-a507-4787-8c84-71955881885c/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/master.py", line 36, in run
    self.server.serve_forever()
  File "/octopus_server/services/bfbb74bc-a507-4787-8c84-71955881885c/lib/python3.11/site-packages/seleniumwire/thirdparty/mitmproxy/net/tcp.py", line 650, in serve_forever
    r, w_, e_ = select.select([self.socket], [], [], poll_interval)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: filedescriptor out of range in select()
Exception managing chrome: Unable to discover proper chromedriver version in offline mode
```

**Comment by asyncfncom** [comment]
done
